### ISSUE TITLE
Scoping: Version 0.1.0

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#195]
As a PO, I would like to have the BeaconCMS version 0.1.0 with the following features available:

<h1>VERSION 0.1.0</h1>

<h2>Pages</h2>

- [ ] Pages: Sorting and Pagination BeaconCMS/beacon_live_admin/issues/87

<h3>Components and Pages</h3>

- [ ] Components and Pages: Preview page before publishing BeaconCMS/beacon_live_admin/issues/59
- [ ] Components and Pages: User-defined function components BeaconCMS/beacon/issues/84
- [ ] Components and Pages: PageEventHandlers: validate event handler code BeaconCMS/beacon_live_admin/issues/46

<h3>General Improvements</h3>

- [x] General Improvements: Add a visual feedback on save operations BeaconCMS/beacon_live_admin/issues/56
- [ ] General Improvements: Create and modify data source at runtime BeaconCMS/beacon_live_admin/issues/68
- [ ] General Improvements: CI - run tests on multiple databases BeaconCMS/beacon/issues/94
- [ ] General Improvements: Documentation and guides BeaconCMS/beacon/issues/228
- [ ] General Improvements: Onboarding concerns causing a barrier to use BeaconCMS/beacon/issues/304
- [ ] General Improvements: Skip invalid pages that fail to load BeaconCMS/beacon/issues/367
- [x] General Improvements: Support Phoenix LiveView v0.20 BeaconCMS/beacon/issues/374

<h3>Hosting and Tenant</h3>

- [ ] Hosting and Tenant: Multiple domains hosting BeaconCMS/beacon/issues/95
- [ ] Hosting and Tenant: Add site selector on navbar BeaconCMS/beacon_live_admin/issues/8

<h3>Layouts</h3>

- [ ] Layouts: Sorting and Pagination BeaconCMS/beacon_live_admin/issues/86

<h3>Components</h3>

- [ ] Components: Sorting and Pagination BeaconCMS/beacon_live_admin/issues/88

<h3>Media Library</h3>

- [ ] Media Library: Sorting and Pagination BeaconCMS/beacon_live_admin/issues/21

<h3>Page Builder</h3>

- [x] Page Builder: Page Builder Improvements BeaconCMS/beacon-ui-builder/issues/2
- [ ] Page Builder: Component to load embedded resources (oEmbed) BeaconCMS/beacon/issues/349

<h3>Editor</h3>

- [ ] Editor: Extend markdown to support HEEx features BeaconCMS/beacon_live_admin/issues/28
- [x] Editor: Creating libraries to implement the foundation of markdown BeaconCMS/beacon/issues/351

<h3>Bugs</h3>

- [x] BUG: Save button not persisting the changes BeaconCMS/beacon_live_admin/issues/85
- [ ] BUG: Tailwind runtime.css potential problem? BeaconCMS/beacon/issues/135
- [x] BUG: Tailwind compiler - parse source from loaded templates BeaconCMS/beacon/issues/194

<h3>Route and Resource Loading</h3>

- [x] Route and Resource Loading: Layout Resource Links - remove empty keys BeaconCMS/beacon_live_admin/issues/64
- [x] Route and Resource Loading: Support error pages BeaconCMS/beacon/issues/137
- [ ] Route and Resource Loading: Add function components to blueprint components BeaconCMS/beacon/issues/341

<h3>Extension</h3>

- [ ] Extension: Rename behaviors modules BeaconCMS/beacon/issues/223

<h3>`beacon.install`</h3>

- [ ] `beacon.install`: Don't allow sites starting with `beacon_` BeaconCMS/beacon/issues/333

<h3>Page variants</h3>

- [x] Page Variants: Error pages BeaconCMS/beacon_live_admin/issues/60

**Comment by AZholtkevych** [comment]
FYI @bcardarella @leandrocp @adam-phillips @cibernox . Guys please review and let me know your thoughts here
