### ISSUE TITLE
Scoping: Q3

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#250]
As a PO, I would like to have an admin panel for the BeaconCMS. In Q3 we're aiming to finish Phase 1, which consists of next features:

<h1>Q3</h1>

<h2>CORE</h2>

<h3>Hosting and Tenant</h3>

- [ ] Multiple domain hosting #95 
- [ ] Compress CSS and JSS using Brotli #159 

<h3>Asset Manager</h3>

- [ ] Smart image crop & scale #198 

<h3>Webfiles and Metatags</h3>

- [ ] Generate `sitemap.xml` #169 
- [ ] Generate `robots.txt` #219 
- [ ] Include sitemap URL in `robots.txt` #220 
- [ ] Upload and serve app icons #185 
- ~~Upload and serve avatar images #234~~ **WILL NOT SUPPORT**

<h3>Components and Pages</h3>

- [ ] Make stylesheets optional #150 
- [ ] Preserve scroll position #123 
- [ ] User-defined function components #84 
- [ ] Component editing #240 

<h3>Route and resource Loading</h3>

- [ ] Support partial segments on paths #161 
- [ ] Support error pages #137 
- [ ] Page update notification and reload #179 

<h2>ADMIN</h2>

<h3>Asset Manager Page</h3>

- [ ] Pages using assets #207 
- [ ] Preview asset before publishing #233 

<h3>Webfiles and Metatags</h3>

- ~~Upload and serve avatar images #234~~ **WILL NOT SUPPORT**

<h3>Editor</h3>

- [ ] Extend markdown to support HEEx features #191
