### ISSUE TITLE
Augment external resource links options

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#322]
Currently Beacon supports adding [`stylesheet_urls` to layouts](https://github.com/BeaconCMS/beacon/blob/6389ce57f477eba9bb14d980b173ad845794578d/lib/beacon/content/layout.ex#L24) which are [injected into the `<head>`](https://github.com/BeaconCMS/beacon/blob/6389ce57f477eba9bb14d980b173ad845794578d/lib/beacon_web/components/layouts/runtime.html.heex#L10) but we need to:

1 - Support more options besides `rel="stylesheet"`. For example to load fonts as:

```html
   <link
    rel="preload"
    href="https://mycdn.com/manrope-v13-latin-latin-ext-regular.woff2"
    as="font"
    type="font/woff2"
    crossorigin="anonymous" />
```

2 - Allow editing that field in LiveAdmin, see https://github.com/BeaconCMS/beacon_live_admin/issues/41

---

The implementation will be very similar to meta tags where we have a list of maps and each attribute of `<link>` is defined as key/value of that map, for example the link above would look like:

```elixir
%Layout{
  resource_links: [
    %{
      rel: "preload",
      href: "https://mycdn.com/manrope-v13-latin-latin-ext-regular.woff2",
      as: "font",
      type: "font/woff2",
      crossorigin: "anonymous"
    }
  ]
}
```

### Tasks

- [ ] Rename [`stylesheet_urls`](https://github.com/BeaconCMS/beacon/blob/6389ce57f477eba9bb14d980b173ad845794578d/lib/beacon/content/layout.ex#L34) to `resource_links`
- [ ]  Change that field data type from `[String.t]` to `[map()]`
- [ ] Create a migration to migrate existing data to the new data structure
- [ ] Rename [linked_stylesheets/1](https://github.com/BeaconCMS/beacon/blob/6389ce57f477eba9bb14d980b173ad845794578d/lib/beacon_web/components/layouts/runtime.html.heex#L10) and change it to render each `<link>` with attrs
- [ ] Bump layout version similar to https://github.com/BeaconCMS/beacon/commit/6389ce57f477eba9bb14d980b173ad845794578d

### Refs
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link
