### ISSUE TITLE
SCOPE V0.1.0

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon#452]
<h1>VERSION 0.1.0</h1>

<h2>Beacon</h2>

- [ ] Components and Pages: User-defined function components BeaconCMS/beacon/issues/84
- [ ] Route and Resource Loading: Add function components to blueprint components BeaconCMS/beacon/issues/341
- [ ] General Improvements: Skip invalid pages that fail to load BeaconCMS/beacon/issues/367
- [ ] General Improvements: CI - run tests on multiple databases BeaconCMS/beacon/issues/94
- [ ] General Improvements: Onboarding concerns causing a barrier to use BeaconCMS/beacon/issues/304
- [ ] BUG: Tailwind runtime.css potential problem? BeaconCMS/beacon/issues/135
- [x] Invalid routes should error gracefully BeaconCMS/beacon/issues/409
- [ ] Failed to resolve default tailwind config BeaconCMS/beacon/issues/440
- [ ] Page Builder: Component to load embedded resources (oEmbed) BeaconCMS/beacon/issues/349
- [x] Expose query params in assigns BeaconCMS/beacon/issues/428
- [x] Extension: Rename behaviors modules BeaconCMS/beacon/issues/223
- [x] Page Builder: Featured pages component BeaconCMS/beacon/issues/357
- [x] Hosting and Tenant: Multiple domains hosting BeaconCMS/beacon/issues/95
- [x] Page Builder: Reading time component BeaconCMS/beacon/issues/358
- [x] BUG: Tailwind compiler - parse source from loaded templates BeaconCMS/beacon/issues/194
- [x] `beacon.install`: Don't allow sites starting with `beacon_` BeaconCMS/beacon/issues/333
- [x] Route and Resource Loading: Add `--path` to `beacon.install` generator BeaconCMS/beacon/issues/306
- [x] Route and Resource Loading: Support error pages BeaconCMS/beacon/issues/137
- [x] Editor: Creating libraries to implement the foundation of markdown BeaconCMS/beacon/issues/351
- [x] General Improvements: Support Phoenix LiveView v0.20 BeaconCMS/beacon/issues/374
- [x] General Improvements: Documentation and guides BeaconCMS/beacon/issues/228
- [x] Revisit CSS compiler lifecycle BeaconCMS/beacon/issues/392
- [x] Proposal: Plausible integration as a plugin BeaconCMS/beacon/issues/291
- [x] Enforce paths starting with a trailing slash `/` BeaconCMS/beacon/issues/395
- [x] `:cowboy_clock.rfc1123/1` is undefined BeaconCMS/beacon/issues/406
- [x] Issue Compiling With `phoenix_html` Version `4.0.0` BeaconCMS/beacon/issues/403
- [x] Redesign resource loading BeaconCMS/beacon/pull/434
- [x] Incorrect page is rendered after reconnecting BeaconCMS/beacon/issues/437
- [x] CI remove deps.compile BeaconCMS/beacon/pull/436
- ~~Webfiles and Metatags: Include sitemap URL in `robots.txt` BeaconCMS/beacon/pull/436~~ REJECTED IN FAVOR OF BeaconCMS/beacon/issues/219

<h2>Beacon Live Admin</h2>

- [ ] Layouts: Sorting and Pagination BeaconCMS/beacon_live_admin/issues/86
- [ ] UX - Collapsible Sidebar BeaconCMS/beacon_live_admin/issues/105
- [x] Resource links not saving on a Layout BeaconCMS/beacon_live_admin/issues/103
- [ ] Components: Sorting and Pagination BeaconCMS/beacon_live_admin/issues/88
- [x] Components and Pages: Preview page before publishing and Page Builder improvements BeaconCMS/beacon_live_admin/issues/59
- [x] Media Library: Sorting and Pagination BeaconCMS/beacon_live_admin/issues/21
- [x] Components and Pages: PageEventHandlers: validate event handler code BeaconCMS/beacon_live_admin/issues/46
- [x] General Improvements: Create and modify data source at runtime BeaconCMS/beacon_live_admin/issues/68
- [x] Hosting and Tenant: Add site selector on navbar BeaconCMS/beacon_live_admin/issues/8
- [x] Pages: Sorting and Pagination BeaconCMS/beacon_live_admin/issues/87
- [x] Page Builder: Page Builder Improvements BeaconCMS/beacon-ui-builder/issues/2
- [x] Page Variants:  Error pages BeaconCMS/beacon_live_admin/issues/60
- [x] Route and Resource Loading: Layout Resource Links - remove empty keys BeaconCMS/beacon_live_admin/issues/64
- [x] General Improvements: Add a visual feedback on save operations BeaconCMS/beacon_live_admin/issues/56
- [x] BUG: Save button not persisting the changes BeaconCMS/beacon_live_admin/issues/85
- [x] Support LiveView v0.20.3+ BeaconCMS/beacon_live_admin/pull/101
- ~~BUG: Media Library crashes in production BeaconCMS/beacon_live_admin/pull/101~~ CAN'T REPRODUCE

**Comment by leandrocp** [comment]
Closing in favor of https://github.com/BeaconCMS/beacon/milestone/1 and https://github.com/BeaconCMS/beacon_live_admin/milestone/1
