### ISSUE TITLE
Docs and Guides

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#472]
Meta issue to track all the work necessary on docs and guides for v0.1

## Beacon
- [x] CHANGELOG
- [x] #473
- [x] #474
- [x] Update ex_doc
- [x] Update the installation guide to fix and improve it based on feedback received
- [x] Update the "your first site" guide to fix and improve it based on feedback received
- [x] Review [groups](https://github.com/BeaconCMS/beacon/blob/ffbfb3d80574e7528d3aa47f5e8eda90813c8d0b/mix.exs#L111) - modules may have been added or removed or are now `@moduledoc false`
- [x] Review module docs - it's not viable to document all the ~100 files we have at this moment so we need to add `@moduledoc false` to private modules or modules that do not impact users. Others we need to review module and functions docs adding a summary, examples, and notes.
- [x] Review and add missing `@spec` to public functions, eg: `Content`, `MediaLibrary` - only in the main API (main modules)
- [x] Review [`Beacon`](https://github.com/BeaconCMS/beacon/blob/ffbfb3d80574e7528d3aa47f5e8eda90813c8d0b/lib/beacon/beacon.ex#L2) docs
- ~List all [authz operations](https://github.com/BeaconCMS/beacon/blob/ffbfb3d80574e7528d3aa47f5e8eda90813c8d0b/lib/beacon/authorization.ex#L36) available~ (removed)
- [x] Write a "publish a blog" recipe that calls `Content.list_published_pages/2` to list most recent pages and filter by tag
- [x] Write a quick guide showing the usage of [beacon assigns](https://github.com/BeaconCMS/beacon/blob/main/lib/beacon_web/beacon_assigns.ex), ie: calling `@beacon` in templates to access data like site name, path/query params, etc.
- [x] Brainstorm other [guides](https://github.com/BeaconCMS/beacon/tree/main/guides/recipes) that makes sense to write for v0.1

## Beacon Live Admin
- [x] CHANGELOG
- [x] Review guides
- [x] Review module docs
- [x] Review function docs

## Beacon Demo
- [ ] Update [beacon_demo](https://github.com/BeaconCMS/beacon_demo) with latest changes
